### PR TITLE
Fix responsive layout issues (resolve #162, resolve #169)

### LINKED ISSUE #162: Fix instructor list item stats
Stats on mobile are squished:

img_0736

Full stats should display on both instructor list item and instructor screen

### LINKED ISSUE #169: Fix horizontal overflow
Some content doesn't wrap. All content should wrap by default and overflow with scroll for code snippets.

screen shot 2017-03-16 at 7 17 10 pm

### PR DESCRIPTION
**Pull request by trevordmiller**
# Changes

- Fix instructor list item stat responsive layout issues and make them look a little better
- Fix lesson long string overflow responsive layout issues

# Result For User

instructor-list-item-stats

break-word

---

### CODE REVIEW

File: src/components/LessonList/components/PaginatedLessonList/components/LessonListItem/index.js [hunk 1]
```diff
@@ -7,7 +7,12 @@ import LessonActions from 'components/LessonActions'
 export default ({lesson, requestCurrentPage}) => {
   const {instructor} = lesson
   return (
-    <div className='flex items-start'>
+    <div
+      className='flex items-start'
+      style={{
+        wordBreak: 'break-word',
+      }}
```
Comment (trevordmiller) [inline src/components/LessonList/components/PaginatedLessonList/components/LessonListItem/index.js:14]: Allows long code strings and urls to break without overflowing the container

File: src/screens/Instructors/components/InstructorListsByStatesCard/components/InstructorList/components/InstructorListItem/index.js [hunk 2]
```diff
@@ -1,65 +1,73 @@
...
+      }
+      {instructor.published_lessons
+        ? <div className='mt3'>
+            <LessonGroupsStat
+              label={publishedTitleText}
+              count={instructor.published_lessons}
+            /> 
+          </div>
+        : null
+      }
```
Comment (trevordmiller) [inline src/screens/Instructors/components/InstructorListsByStatesCard/components/InstructorList/components/InstructorListItem/index.js:69]: Normally I would map over the four items above to reduce the replicated logic and styles, but I'm keeping it inline because of the discussions we had about avoiding being ultra DRY.

**Review by tayiorbeii — APPROVED** [review]
